module Database.Package.Readme.Decode exposing (..)

{-| Generated by elm-json-interop.
-}

import Database.Package.Readme as A
import Elm.Docs.Decode
import Elm.Module.NameDict.Decode
import Json.Decode as D exposing (Decoder)
import Utils.Json.Decode_ as D_


readme : Decoder A.Readme
readme =
    D.map2
        (\v1 v2 ->
            { readme = v1
            , modules = v2
            }
        )
        (D.field "readme" D.string)
        (D.field "modules" (Elm.Module.NameDict.Decode.nameDict (D.list Elm.Docs.Decode.block)))
