module Database.Package.Readme.Encode exposing (..)

{-| Generated by elm-json-interop.
-}

import Database.Package.Readme as A
import Elm.Docs.Encode
import Elm.Module.NameDict.Encode
import Json.Encode as E
import Utils.Json.Encode_ as E_ exposing (Encoder)


readme : Encoder A.Readme
readme =
    \v1 ->
        E.object
            [ ( "readme"
              , E.string v1.readme
              )
            , ( "modules"
              , Elm.Module.NameDict.Encode.nameDict moduleReadme v1.modules
              )
            ]


moduleReadme : Encoder A.ModuleReadme
moduleReadme =
    \v1 ->
        E.object
            [ ( "readme"
              , E.string v1.readme
              )
            , ( "unions"
              , E_.dict E.string Elm.Docs.Encode.union v1.unions
              )
            , ( "aliases"
              , E_.dict E.string Elm.Docs.Encode.alias v1.aliases
              )
            , ( "values"
              , E_.dict E.string Elm.Docs.Encode.value v1.values
              )
            , ( "binops"
              , E_.dict E.string Elm.Docs.Encode.binop v1.binops
              )
            ]
