module Elm.Module.NameDict.Decode exposing (..)

{-| Generated by elm-json-interop.
-}

import Elm.Module.NameDict as A
import Json.Decode as D exposing (Decoder)
import Utils.Json.Decode_ as D_


nameDict : Decoder v -> Decoder (A.NameDict v)
nameDict v =
    D.map A.NameDict (D_.dict D.string v)
